### ISSUE TITLE
Plugin doesn't support Gradle configuration cache

### ISSUE THREAD

**Issue by Maxr1998** [CleverPumpkin/Proguard-Dictionaries-Generator#11]
Relevant error message:
```
Configuration cache problems found in this build.

3 problems were found storing the configuration cache, 1 of which seems unique.
- Task `:app:generateProguardDictionaries` of type `ru.cleverpumpkin.plugin.ProguardR8DictionaryGeneratorTask`: invocation of 'Task.project' at execution time is unsupported.
  See https://docs.gradle.org/8.1.1/userguide/configuration_cache.html#config_cache:requirements:use_project_during_execution
```

The `project.projectDir` call needs to be replaced in the Task to resolve this issue and make the task compatible with the configuration cache. This should be possible by wrapping the directory names in `ObjectFactory.fileCollection().from(directoryNames)`.

I would be willing to fix this myself, I'd just need you to merge & release the fix afterwards.

**Comment by eakteam** [comment]
> Relevant error message:
> 
> ```
> Configuration cache problems found in this build.
> 
> 3 problems were found storing the configuration cache, 1 of which seems unique.
> - Task `:app:generateProguardDictionaries` of type `ru.cleverpumpkin.plugin.ProguardR8DictionaryGeneratorTask`: invocation of 'Task.project' at execution time is unsupported.
>   See https://docs.gradle.org/8.1.1/userguide/configuration_cache.html#config_cache:requirements:use_project_during_execution
> ```
> 
> The `project.projectDir` call needs to be replaced in the Task to resolve this issue and make the task compatible with the configuration cache. This should be possible by wrapping the directory names in `ObjectFactory.fileCollection().from(directoryNames)`.
> 
> I would be willing to fix this myself, I'd just need you to merge & release the fix afterwards.

Have you implemented the solution anywhere? Thanks

**Comment by Maxr1998** [comment]
No, not yet. I'd like to get some feedback from a maintainer first.

**Comment by eakteam** [comment]
@Maxr1998 I think that this plugin is deprecated. If you have found any solution meantime it would be great.

**Comment by Maxr1998** [comment]
Seems so. I'm already planning to fork and update it myself. I'll update you once I have it published.

**Comment by Maxr1998** [comment]
The updated plugin has been published to the [Gradle plugin portal](https://plugins.gradle.org/plugin/de.maxr1998.proguard-dictionaries-generator).

Source code is available at [Maxr1998/Proguard-Dictionaries-Generator](https://github.com/Maxr1998/Proguard-Dictionaries-Generator).

Since I maintain my own plugin version now, I'm closing this issue.
