### ISSUE TITLE
Cannot find task for Android Studio 3.6 Canary 8 & UP

### ISSUE THREAD

**Issue by eakteam** [CleverPumpkin/Proguard-Dictionaries-Generator#2]
It shows `Neither proguard tasks, nor R8 tasks were not found`
I have looked up in the source code of `this plugin` and in the `gradle tasks` and it seems that this plugin is using old task name :
`const val TARGET_R8_TASK = "transformClassesAndResourcesWithR8For"` 

So, there should be added another val : 
`const val TARGET_R8_TASK_NEW = "minifyReleaseWithR8"`

It seems that new gradle plugin use `"minifyReleaseWithR8"` for this task

EDIT 09/07/2019 : 

Still not working with latest Android Studio 3.6 Canary 8,9,10 etc. Please update gradle task.

**Comment by eakteam** [comment]
Any news ? Is this project(plugin) still supported ? This is very helpful plugin and the change to support latest Android Builds is very important, because for the moment it is not usable with latest Gradle/Android Studio... We need to manually modify to continue to use it.

Thanks for the work and best regards.

**Comment by creati8e** [comment]
Hi! Yes, this project isn't abandoned. I am a bit lazy, but will try to fix it soon. (Probably today)

**Comment by eakteam** [comment]
Hi creati8e, thanks for your fast response. It would be great if you make a solution for that. Also please see another bug i have postet for obfuscation improvements

**Comment by creati8e** [comment]
Yes, i will include both fixes!

**Comment by eakteam** [comment]
Any news about when it will be released ? Thank you

**Comment by creati8e** [comment]
I am frustrated. I've made a commit with fix in the same day. But I can't made a push nor create pull request due to lack of permissions.

**Comment by eakteam** [comment]
I don't know why it happens but you can try to upload jar file at maven or other repositories ? Because it is very important really....

Thanks

**Comment by eakteam** [comment]
Cannot download and use V. 1.0.7 still, i saw that you have made some changes, but Gradle Plugin cannot find & download it ... Any news ?
Thanks.

P.s : The only solution for the moment is to download this project offline and implement manually to Android Studio, but it should be solved.

Best Regards and thanks for the work.

**Comment by eakteam** [comment]
Just to add something more : 

It would be better to skip issues in following if you add in the releases section precompiled .zip plugin for Android Studio, so if something wrong is happening, we can be able to download .zip file and add directly to AS, without manually compiling and packaging it. Thanks again for your work, i understand that this is minor issue but for my case, i cannot use latest Studio because of this problem and it is very time consuming to clone this repository and make it on my own.

**Comment by creati8e** [comment]
Fixed

**Comment by eakteam** [comment]
Thank you ! I confirm that it is working finally :) :)
