### ISSUE TITLE
Cannot use V. 1.0.7

### ISSUE THREAD

**Issue by eakteam** [CleverPumpkin/Proguard-Dictionaries-Generator#4]
After many days waiting for a fix for this minor issue, i choose to open another bug report because gradle cannot find and download new version. I understand that maybe it is because some other problems with maven or something like this, but please make a solution for that !

Android Studio 3.6 is in BETA since 4 or more days before and it should be solved.

Thanks again !

**Comment by creati8e** [comment]
Hi! I am really really sorry but we've fell into many routines related to credentials/accesses and so on because i'm not an employee of this company anymore. Plugin is published. Sorry for inconvenience and your infinite enthusiasm about this issue.

**Comment by creati8e** [comment]
Fixed

**Comment by eakteam** [comment]
Thank you ! I confirm that it is working finally :) :)
